{% set name = "qtpyinheritance" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/klauer/qtpyinheritance/archive/v{{ version }}.tar.gz
  sha256: 493a854a36bd0e05378dbf0fbd7b36d0bc1f21c9b93426afe8514417b1ce7c4b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - qtpy

test:
  imports:
    - qtpyinheritance
  requires:
    - pyqt

about:
  home: https://github.com/klauer/qtpyinheritance
  dev_url: https://github.com/klauer/qtpyinheritance
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'qtpy tools for dealing with property/slot forwarding from base classes and inheritance in general'

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
