{% set name = "qtpyinheritance" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/klauer/qtpyinheritance/archive/v{{ version }}.tar.gz
  sha256: a1fefe895598cb4cdb3e6f2acdaf5ed04dcd33d4087266e9d1d4498a664b4e5e

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - qtpyinheritance
  requires:
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/klauer/qtpyinheritance
  dev_url: https://github.com/klauer/qtpyinheritance
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'qtpy tools for dealing with property/slot forwarding from base classes and inheritance in general'

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
